id = "replique"
name = "Replique"
version = "0.1.0"
schema_version = 1
description = "Live diagnostics for Replique dialogue files"
authors = ["Théo Plénet"]
repository = "https://github.com/Galdormin/replique"
languages = ["languages/replique"]

[lib]
kind = "Rust"
version = "0.7.0"

[grammars.replique]
repository = "https://github.com/Galdormin/replique"
rev = "16eef7316e1f649dca03c352f8e8c4d4130ea9c4"
path = "editors/tree-sitter-replique"

[language_servers.replique-lsp]
name = "Replique Language Server"
languages = ["Replique"]
