[package]
name = "bevy_replique"
description = "Bevy plugin for Replique, a pure rust dialogue manager"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"

[dependencies]
replique = { workspace = true }
bevy_replique_derive = { workspace = true }

bevy = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bevy = { version = "0.19", default-features = false, features = ["ui", "2d"] }
