[package]
name = "replique"
description = "A pure Rust dialogue system"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords = ["dialogue", "narrative", "gamedev", "yarnspinner", "parser"]
categories = ["game-development", "parser-implementations"]
readme = "../../README.md"

[dependencies]
thiserror = { workspace = true }
logos = "0.16"

[dev-dependencies]
insta = "1.48"
proptest = "1.11"
