/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 43
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 13
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__newline = 2,
  sym_comment = 3,
  anon_sym_COLON_EQ = 4,
  sym_node_end = 5,
  anon_sym_EQ_GT = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_GT_GT = 8,
  anon_sym_LBRACKlet = 9,
  anon_sym_EQ = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LBRACKif = 12,
  anon_sym_LBRACKelif = 13,
  anon_sym_LBRACKelse = 14,
  sym_speaker = 15,
  sym__bare_text = 16,
  sym_text = 17,
  anon_sym_LPAREN = 18,
  anon_sym_COMMA = 19,
  anon_sym_RPAREN = 20,
  anon_sym_LPAREN2 = 21,
  anon_sym_not = 22,
  anon_sym_BANG = 23,
  anon_sym_DASH = 24,
  anon_sym_or = 25,
  anon_sym_PIPE_PIPE = 26,
  anon_sym_and = 27,
  anon_sym_AMP_AMP = 28,
  anon_sym_EQ_EQ = 29,
  anon_sym_BANG_EQ = 30,
  anon_sym_LT = 31,
  anon_sym_LT_EQ = 32,
  anon_sym_GT = 33,
  anon_sym_GT_EQ = 34,
  anon_sym_PLUS = 35,
  anon_sym_STAR = 36,
  anon_sym_SLASH = 37,
  sym_variable = 38,
  sym_number = 39,
  sym_string = 40,
  anon_sym_true = 41,
  anon_sym_false = 42,
  sym_source_file = 43,
  sym__statement = 44,
  sym_node_start = 45,
  sym_jump = 46,
  sym_node_name = 47,
  sym_choice = 48,
  sym_command = 49,
  sym_let_statement = 50,
  sym_if_statement = 51,
  sym_elif_statement = 52,
  sym_else_statement = 53,
  sym_say = 54,
  sym__expression = 55,
  sym_call = 56,
  sym_function_name = 57,
  sym_parenthesized_expression = 58,
  sym_unary_expression = 59,
  sym_binary_expression = 60,
  sym_boolean = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_call_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_COLON_EQ] = ":=",
  [sym_node_end] = "node_end",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LBRACKlet] = "[let",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACKif] = "[if",
  [anon_sym_LBRACKelif] = "[elif",
  [anon_sym_LBRACKelse] = "[else",
  [sym_speaker] = "speaker",
  [sym__bare_text] = "text",
  [sym_text] = "text",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_not] = "not",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_or] = "or",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_and] = "and",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_variable] = "variable",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_node_start] = "node_start",
  [sym_jump] = "jump",
  [sym_node_name] = "node_name",
  [sym_choice] = "choice",
  [sym_command] = "command",
  [sym_let_statement] = "let_statement",
  [sym_if_statement] = "if_statement",
  [sym_elif_statement] = "elif_statement",
  [sym_else_statement] = "else_statement",
  [sym_say] = "say",
  [sym__expression] = "_expression",
  [sym_call] = "call",
  [sym_function_name] = "function_name",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_node_end] = sym_node_end,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LBRACKlet] = anon_sym_LBRACKlet,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACKif] = anon_sym_LBRACKif,
  [anon_sym_LBRACKelif] = anon_sym_LBRACKelif,
  [anon_sym_LBRACKelse] = anon_sym_LBRACKelse,
  [sym_speaker] = sym_speaker,
  [sym__bare_text] = sym_text,
  [sym_text] = sym_text,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_variable] = sym_variable,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_node_start] = sym_node_start,
  [sym_jump] = sym_jump,
  [sym_node_name] = sym_node_name,
  [sym_choice] = sym_choice,
  [sym_command] = sym_command,
  [sym_let_statement] = sym_let_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_elif_statement] = sym_elif_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_say] = sym_say,
  [sym__expression] = sym__expression,
  [sym_call] = sym_call,
  [sym_function_name] = sym_function_name,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_node_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKelif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKelse] = {
    .visible = true,
    .named = false,
  },
  [sym_speaker] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_node_start] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elif_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_say] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_call = 1,
  field_condition = 2,
  field_name = 3,
  field_operator = 4,
  field_speaker = 5,
  field_target = 6,
  field_text = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_call] = "call",
  [field_condition] = "condition",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_speaker] = "speaker",
  [field_target] = "target",
  [field_text] = "text",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 1},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 1},
  [11] = {.index = 11, .length = 1},
  [12] = {.index = 12, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_speaker, 0},
  [1] =
    {field_text, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_target, 1},
  [4] =
    {field_text, 1},
  [5] =
    {field_call, 1},
  [6] =
    {field_speaker, 0},
    {field_text, 1},
  [8] =
    {field_operator, 0},
  [9] =
    {field_condition, 1},
  [10] =
    {field_name, 0},
  [11] =
    {field_operator, 1},
  [12] =
    {field_name, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 8,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 27,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 28,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 29,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 53,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '!', 76,
        '"', 5,
        '$', 24,
        '&', 6,
        '(', 71,
        ')', 73,
        '*', 89,
        '+', 88,
        ',', 72,
        '-', 78,
        '/', 90,
        ':', 13,
        '<', 83,
        '=', 42,
        '>', 86,
        '[', 15,
        ']', 43,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 75,
        '"', 5,
        '$', 24,
        '(', 74,
        ')', 73,
        '-', 77,
        '/', 8,
        '=', 41,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 12,
        '&', 6,
        '(', 71,
        ')', 73,
        '*', 89,
        '+', 88,
        ',', 72,
        '-', 77,
        '/', 90,
        '<', 83,
        '=', 14,
        '>', 85,
        ']', 43,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 12,
        '&', 6,
        ')', 73,
        '*', 89,
        '+', 88,
        ',', 72,
        '-', 77,
        '/', 90,
        '<', 83,
        '=', 14,
        '>', 85,
        ']', 43,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(93);
      if (lookahead == '\\') ADVANCE(28);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '&') ADVANCE(80);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(60);
      END_STATE();
    case 12:
      if (lookahead == '=') ADVANCE(82);
      END_STATE();
    case 13:
      if (lookahead == '=') ADVANCE(35);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(81);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 18:
      if (lookahead == 'f') ADVANCE(44);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 23:
      if (lookahead == '|') ADVANCE(79);
      END_STATE();
    case 24:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != ':') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(70);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 29:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 1,
        '!', 76,
        '"', 5,
        '$', 24,
        '&', 6,
        '(', 74,
        ')', 73,
        '*', 89,
        '+', 88,
        ',', 72,
        '-', 78,
        '/', 90,
        ':', 13,
        '<', 83,
        '=', 42,
        '>', 86,
        '[', 15,
        ']', 43,
        '|', 23,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    case 30:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 48,
        '-', 49,
        '/', 9,
        ':', 54,
        '=', 55,
        '>', 56,
        '[', 15,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(30);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 31:
      if (eof) ADVANCE(32);
      ADVANCE_MAP(
        '\n', 33,
        '\r', 60,
        '-', 59,
        '/', 10,
        ':', 62,
        '=', 61,
        '>', 61,
        '[', 64,
        '\t', 57,
        ' ', 57,
      );
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_node_end);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACKlet);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(81);
      if (lookahead == '>') ADVANCE(37);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACKif);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACKelif);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACKelse);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_speaker);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '>') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == ':') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '=') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(52);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '>') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(50);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(50);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\r', 60,
        '-', 59,
        '/', 10,
        ':', 62,
        '=', 61,
        '>', 61,
        '[', 64,
        '\t', 57,
        ' ', 57,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(70);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(58);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '>') ADVANCE(70);
      if (lookahead == ':' ||
          lookahead == '=') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == ':') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '>') ADVANCE(70);
      if (lookahead == '-' ||
          lookahead == ':' ||
          lookahead == '=') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead == '=') ADVANCE(70);
      if (lookahead == '-' ||
          lookahead == ':' ||
          lookahead == '>') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead == 'l') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'e') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'f') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'i') ADVANCE(66);
      if (lookahead == 's') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 'l') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == 't') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(82);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(38);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(87);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(87);
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(34);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 31},
  [37] = {.lex_state = 31},
  [38] = {.lex_state = 30},
  [39] = {.lex_state = 30},
  [40] = {.lex_state = 30},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 30},
  [49] = {.lex_state = 30},
  [50] = {.lex_state = 30},
  [51] = {.lex_state = 30},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACKlet] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACKif] = ACTIONS(1),
    [anon_sym_LBRACKelif] = ACTIONS(1),
    [anon_sym_LBRACKelse] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(58),
    [sym__statement] = STATE(2),
    [sym_node_start] = STATE(2),
    [sym_jump] = STATE(2),
    [sym_choice] = STATE(2),
    [sym_command] = STATE(2),
    [sym_let_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_elif_statement] = STATE(2),
    [sym_else_statement] = STATE(2),
    [sym_say] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [sym_node_end] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(13),
    [anon_sym_GT_GT] = ACTIONS(15),
    [anon_sym_LBRACKlet] = ACTIONS(17),
    [anon_sym_LBRACKif] = ACTIONS(19),
    [anon_sym_LBRACKelif] = ACTIONS(21),
    [anon_sym_LBRACKelse] = ACTIONS(23),
    [sym_speaker] = ACTIONS(25),
    [sym__bare_text] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_COLON_EQ,
    ACTIONS(11), 1,
      anon_sym_EQ_GT,
    ACTIONS(13), 1,
      anon_sym_DASH_GT,
    ACTIONS(15), 1,
      anon_sym_GT_GT,
    ACTIONS(17), 1,
      anon_sym_LBRACKlet,
    ACTIONS(19), 1,
      anon_sym_LBRACKif,
    ACTIONS(21), 1,
      anon_sym_LBRACKelif,
    ACTIONS(23), 1,
      anon_sym_LBRACKelse,
    ACTIONS(25), 1,
      sym_speaker,
    ACTIONS(27), 1,
      sym__bare_text,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 2,
      sym__newline,
      sym_node_end,
    STATE(3), 11,
      sym__statement,
      sym_node_start,
      sym_jump,
      sym_choice,
      sym_command,
      sym_let_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_say,
      aux_sym_source_file_repeat1,
  [54] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_COLON_EQ,
    ACTIONS(41), 1,
      anon_sym_EQ_GT,
    ACTIONS(44), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_GT_GT,
    ACTIONS(50), 1,
      anon_sym_LBRACKlet,
    ACTIONS(53), 1,
      anon_sym_LBRACKif,
    ACTIONS(56), 1,
      anon_sym_LBRACKelif,
    ACTIONS(59), 1,
      anon_sym_LBRACKelse,
    ACTIONS(62), 1,
      sym_speaker,
    ACTIONS(65), 1,
      sym__bare_text,
    ACTIONS(35), 2,
      sym__newline,
      sym_node_end,
    STATE(3), 11,
      sym__statement,
      sym_node_start,
      sym_jump,
      sym_choice,
      sym_command,
      sym_let_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_say,
      aux_sym_source_file_repeat1,
  [108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(68), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [136] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(76), 1,
      anon_sym_RPAREN,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(84), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(19), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [176] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(90), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(8), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [216] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(92), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(34), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [253] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(96), 1,
      anon_sym_RPAREN,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    STATE(55), 1,
      aux_sym_call_repeat1,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [294] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(112), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(32), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [331] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(114), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(13), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [368] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(116), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [393] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(120), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(33), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [430] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(122), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [455] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(126), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(21), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [492] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(128), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(22), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [529] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(130), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(23), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [566] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(132), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(24), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [603] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(134), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(25), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [640] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(136), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_call_repeat1,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [681] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(138), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [706] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(142), 13,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [735] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(142), 5,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
  [770] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(142), 7,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
  [803] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(144), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(142), 11,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [834] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(142), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [859] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(146), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(31), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [896] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(148), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [921] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(152), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [946] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(156), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [971] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_identifier,
    ACTIONS(78), 1,
      anon_sym_LPAREN2,
    ACTIONS(80), 1,
      anon_sym_not,
    STATE(64), 1,
      sym_function_name,
    ACTIONS(82), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(160), 3,
      sym_variable,
      sym_number,
      sym_string,
    STATE(35), 6,
      sym__expression,
      sym_call,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [1008] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1044] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1079] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(166), 1,
      anon_sym_RBRACK,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1114] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(168), 1,
      anon_sym_RBRACK,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1149] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_STAR,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
    ACTIONS(98), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(100), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(102), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(106), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(104), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1184] = 4,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    ACTIONS(176), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_text,
    ACTIONS(174), 12,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
      sym__bare_text,
  [1208] = 4,
    ACTIONS(176), 1,
      sym_comment,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(184), 1,
      sym_text,
    ACTIONS(182), 12,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
      sym__bare_text,
  [1232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      sym__bare_text,
    ACTIONS(186), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym__bare_text,
    ACTIONS(190), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1274] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym__bare_text,
    ACTIONS(194), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1295] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym__bare_text,
    ACTIONS(198), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      sym__bare_text,
    ACTIONS(148), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1337] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym__bare_text,
    ACTIONS(202), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1358] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym__bare_text,
    ACTIONS(206), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1379] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym__bare_text,
    ACTIONS(210), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1400] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym__bare_text,
    ACTIONS(214), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      sym__bare_text,
    ACTIONS(152), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      sym__bare_text,
    ACTIONS(218), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1463] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym__bare_text,
    ACTIONS(222), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1484] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym__bare_text,
    ACTIONS(226), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      sym__bare_text,
    ACTIONS(156), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1526] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_call_repeat1,
  [1539] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_call_repeat1,
  [1552] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(40), 1,
      sym_call,
    STATE(61), 1,
      sym_function_name,
  [1565] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      aux_sym_call_repeat1,
  [1578] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(43), 1,
      sym_node_name,
  [1588] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(45), 1,
      sym_node_name,
  [1598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      ts_builtin_sym_end,
  [1605] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_RBRACK,
  [1612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_LPAREN,
  [1626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
  [1633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_variable,
  [1640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 136,
  [SMALL_STATE(6)] = 176,
  [SMALL_STATE(7)] = 216,
  [SMALL_STATE(8)] = 253,
  [SMALL_STATE(9)] = 294,
  [SMALL_STATE(10)] = 331,
  [SMALL_STATE(11)] = 368,
  [SMALL_STATE(12)] = 393,
  [SMALL_STATE(13)] = 430,
  [SMALL_STATE(14)] = 455,
  [SMALL_STATE(15)] = 492,
  [SMALL_STATE(16)] = 529,
  [SMALL_STATE(17)] = 566,
  [SMALL_STATE(18)] = 603,
  [SMALL_STATE(19)] = 640,
  [SMALL_STATE(20)] = 681,
  [SMALL_STATE(21)] = 706,
  [SMALL_STATE(22)] = 735,
  [SMALL_STATE(23)] = 770,
  [SMALL_STATE(24)] = 803,
  [SMALL_STATE(25)] = 834,
  [SMALL_STATE(26)] = 859,
  [SMALL_STATE(27)] = 896,
  [SMALL_STATE(28)] = 921,
  [SMALL_STATE(29)] = 946,
  [SMALL_STATE(30)] = 971,
  [SMALL_STATE(31)] = 1008,
  [SMALL_STATE(32)] = 1044,
  [SMALL_STATE(33)] = 1079,
  [SMALL_STATE(34)] = 1114,
  [SMALL_STATE(35)] = 1149,
  [SMALL_STATE(36)] = 1184,
  [SMALL_STATE(37)] = 1208,
  [SMALL_STATE(38)] = 1232,
  [SMALL_STATE(39)] = 1253,
  [SMALL_STATE(40)] = 1274,
  [SMALL_STATE(41)] = 1295,
  [SMALL_STATE(42)] = 1316,
  [SMALL_STATE(43)] = 1337,
  [SMALL_STATE(44)] = 1358,
  [SMALL_STATE(45)] = 1379,
  [SMALL_STATE(46)] = 1400,
  [SMALL_STATE(47)] = 1421,
  [SMALL_STATE(48)] = 1442,
  [SMALL_STATE(49)] = 1463,
  [SMALL_STATE(50)] = 1484,
  [SMALL_STATE(51)] = 1505,
  [SMALL_STATE(52)] = 1526,
  [SMALL_STATE(53)] = 1539,
  [SMALL_STATE(54)] = 1552,
  [SMALL_STATE(55)] = 1565,
  [SMALL_STATE(56)] = 1578,
  [SMALL_STATE(57)] = 1588,
  [SMALL_STATE(58)] = 1598,
  [SMALL_STATE(59)] = 1605,
  [SMALL_STATE(60)] = 1612,
  [SMALL_STATE(61)] = 1619,
  [SMALL_STATE(62)] = 1626,
  [SMALL_STATE(63)] = 1633,
  [SMALL_STATE(64)] = 1640,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 8),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 8),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 11),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 11),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 10),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 10),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 10),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 10),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 10),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5, 0, 10),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 1, 0, 1),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 1, 0, 1),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 1, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 1, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 1, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 2, 0, 5),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 2, 0, 5),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 6),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 6),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elif_statement, 3, 0, 9),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elif_statement, 3, 0, 9),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, 0, 4),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2, 0, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_name, 1, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_start, 2, 0, 3),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_start, 2, 0, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 9),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 9),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 12),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 12),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 2, 0, 7),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 2, 0, 7),
  [230] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [241] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_replique(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "replique",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
