/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 74
#define ALIAS_COUNT 0
#define TOKEN_COUNT 47
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 18
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__newline = 2,
  sym_comment = 3,
  anon_sym_COLON_EQ = 4,
  sym_node_end = 5,
  anon_sym_EQ_GT = 6,
  anon_sym_DASH_GT = 7,
  anon_sym_GT_GT = 8,
  anon_sym_LBRACKlet = 9,
  anon_sym_EQ = 10,
  anon_sym_RBRACK = 11,
  anon_sym_LBRACKif = 12,
  anon_sym_LBRACKelif = 13,
  anon_sym_LBRACKelse = 14,
  sym_speaker = 15,
  sym__bare_text = 16,
  sym_text = 17,
  anon_sym_LPAREN = 18,
  anon_sym_COMMA = 19,
  anon_sym_RPAREN = 20,
  anon_sym_LBRACE = 21,
  anon_sym_RBRACE = 22,
  anon_sym_COLON = 23,
  sym_attribute = 24,
  anon_sym_LPAREN2 = 25,
  anon_sym_not = 26,
  anon_sym_BANG = 27,
  anon_sym_DASH = 28,
  anon_sym_or = 29,
  anon_sym_PIPE_PIPE = 30,
  anon_sym_and = 31,
  anon_sym_AMP_AMP = 32,
  anon_sym_EQ_EQ = 33,
  anon_sym_BANG_EQ = 34,
  anon_sym_LT = 35,
  anon_sym_LT_EQ = 36,
  anon_sym_GT = 37,
  anon_sym_GT_EQ = 38,
  anon_sym_PLUS = 39,
  anon_sym_STAR = 40,
  anon_sym_SLASH = 41,
  sym_variable = 42,
  sym_number = 43,
  sym_string = 44,
  anon_sym_true = 45,
  anon_sym_false = 46,
  sym_source_file = 47,
  sym__statement = 48,
  sym_node_start = 49,
  sym_jump = 50,
  sym_node_name = 51,
  sym_choice = 52,
  sym_command = 53,
  sym_let_statement = 54,
  sym_if_statement = 55,
  sym_elif_statement = 56,
  sym_else_statement = 57,
  sym_say = 58,
  sym__expression = 59,
  sym_call = 60,
  sym_function_name = 61,
  sym_dict = 62,
  sym_dict_entry = 63,
  sym_dict_key = 64,
  sym_attribute_expression = 65,
  sym_parenthesized_expression = 66,
  sym_unary_expression = 67,
  sym_binary_expression = 68,
  sym_boolean = 69,
  aux_sym_source_file_repeat1 = 70,
  aux_sym_let_statement_repeat1 = 71,
  aux_sym_call_repeat1 = 72,
  aux_sym_dict_repeat1 = 73,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [anon_sym_COLON_EQ] = ":=",
  [sym_node_end] = "node_end",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_LBRACKlet] = "[let",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACKif] = "[if",
  [anon_sym_LBRACKelif] = "[elif",
  [anon_sym_LBRACKelse] = "[else",
  [sym_speaker] = "speaker",
  [sym__bare_text] = "text",
  [sym_text] = "text",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_attribute] = "attribute",
  [anon_sym_LPAREN2] = "(",
  [anon_sym_not] = "not",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_or] = "or",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_and] = "and",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_variable] = "variable",
  [sym_number] = "number",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_node_start] = "node_start",
  [sym_jump] = "jump",
  [sym_node_name] = "node_name",
  [sym_choice] = "choice",
  [sym_command] = "command",
  [sym_let_statement] = "let_statement",
  [sym_if_statement] = "if_statement",
  [sym_elif_statement] = "elif_statement",
  [sym_else_statement] = "else_statement",
  [sym_say] = "say",
  [sym__expression] = "_expression",
  [sym_call] = "call",
  [sym_function_name] = "function_name",
  [sym_dict] = "dict",
  [sym_dict_entry] = "dict_entry",
  [sym_dict_key] = "dict_key",
  [sym_attribute_expression] = "attribute_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_boolean] = "boolean",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_let_statement_repeat1] = "let_statement_repeat1",
  [aux_sym_call_repeat1] = "call_repeat1",
  [aux_sym_dict_repeat1] = "dict_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_node_end] = sym_node_end,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_LBRACKlet] = anon_sym_LBRACKlet,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACKif] = anon_sym_LBRACKif,
  [anon_sym_LBRACKelif] = anon_sym_LBRACKelif,
  [anon_sym_LBRACKelse] = anon_sym_LBRACKelse,
  [sym_speaker] = sym_speaker,
  [sym__bare_text] = sym_text,
  [sym_text] = sym_text,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_attribute] = sym_attribute,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_variable] = sym_variable,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_node_start] = sym_node_start,
  [sym_jump] = sym_jump,
  [sym_node_name] = sym_node_name,
  [sym_choice] = sym_choice,
  [sym_command] = sym_command,
  [sym_let_statement] = sym_let_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_elif_statement] = sym_elif_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_say] = sym_say,
  [sym__expression] = sym__expression,
  [sym_call] = sym_call,
  [sym_function_name] = sym_function_name,
  [sym_dict] = sym_dict,
  [sym_dict_entry] = sym_dict_entry,
  [sym_dict_key] = sym_dict_key,
  [sym_attribute_expression] = sym_attribute_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_boolean] = sym_boolean,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_let_statement_repeat1] = aux_sym_let_statement_repeat1,
  [aux_sym_call_repeat1] = aux_sym_call_repeat1,
  [aux_sym_dict_repeat1] = aux_sym_dict_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_node_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKelif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKelse] = {
    .visible = true,
    .named = false,
  },
  [sym_speaker] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_node_start] = {
    .visible = true,
    .named = true,
  },
  [sym_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_node_name] = {
    .visible = true,
    .named = true,
  },
  [sym_choice] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elif_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_say] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_key] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_let_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dict_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attribute = 1,
  field_base = 2,
  field_call = 3,
  field_condition = 4,
  field_key = 5,
  field_name = 6,
  field_operator = 7,
  field_speaker = 8,
  field_target = 9,
  field_text = 10,
  field_value = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attribute] = "attribute",
  [field_base] = "base",
  [field_call] = "call",
  [field_condition] = "condition",
  [field_key] = "key",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_speaker] = "speaker",
  [field_target] = "target",
  [field_text] = "text",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 2},
  [8] = {.index = 8, .length = 1},
  [9] = {.index = 9, .length = 1},
  [10] = {.index = 10, .length = 2},
  [11] = {.index = 12, .length = 1},
  [12] = {.index = 13, .length = 1},
  [13] = {.index = 14, .length = 2},
  [14] = {.index = 16, .length = 1},
  [15] = {.index = 17, .length = 2},
  [16] = {.index = 19, .length = 2},
  [17] = {.index = 21, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_speaker, 0},
  [1] =
    {field_text, 0},
  [2] =
    {field_name, 1},
  [3] =
    {field_target, 1},
  [4] =
    {field_text, 1},
  [5] =
    {field_call, 1},
  [6] =
    {field_speaker, 0},
    {field_text, 1},
  [8] =
    {field_attribute, 0},
  [9] =
    {field_operator, 0},
  [10] =
    {field_attribute, 1, .inherited = true},
    {field_base, 0},
  [12] =
    {field_condition, 1},
  [13] =
    {field_name, 0},
  [14] =
    {field_attribute, 0, .inherited = true},
    {field_attribute, 1, .inherited = true},
  [16] =
    {field_operator, 1},
  [17] =
    {field_name, 1},
    {field_value, 3},
  [19] =
    {field_key, 0},
    {field_value, 2},
  [21] =
    {field_attribute, 2, .inherited = true},
    {field_name, 1},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 38,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 23,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 24,
  [57] = 57,
  [58] = 58,
  [59] = 25,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 67,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 35,
        '\r', 1,
        '!', 84,
        '"', 7,
        '$', 25,
        '&', 8,
        '(', 74,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 86,
        '.', 26,
        '/', 98,
        ':', 80,
        '<', 91,
        '=', 45,
        '>', 94,
        '[', 16,
        ']', 46,
        '{', 77,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(35);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 83,
        '"', 7,
        '$', 25,
        '(', 82,
        ')', 76,
        '-', 85,
        '.', 26,
        '/', 10,
        ':', 79,
        '=', 43,
        '{', 77,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '!', 14,
        '&', 8,
        '(', 74,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 85,
        '.', 26,
        '/', 98,
        '<', 91,
        '=', 44,
        '>', 93,
        ']', 46,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '!', 14,
        '&', 8,
        '(', 74,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 85,
        '.', 26,
        '/', 98,
        '<', 91,
        '=', 15,
        '>', 93,
        ']', 46,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '!', 14,
        '&', 8,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 85,
        '.', 26,
        '/', 98,
        '<', 91,
        '=', 44,
        '>', 93,
        ']', 46,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '!', 14,
        '&', 8,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 85,
        '.', 26,
        '/', 98,
        '<', 91,
        '=', 15,
        '>', 93,
        ']', 46,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(101);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '&') ADVANCE(88);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 12:
      if (lookahead == '/') ADVANCE(36);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(63);
      END_STATE();
    case 14:
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 15:
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 24:
      if (lookahead == '|') ADVANCE(87);
      END_STATE();
    case 25:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 26:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/' &&
          lookahead != ':') ADVANCE(53);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(55);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '/') ADVANCE(73);
      END_STATE();
    case 30:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 31:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 35,
        '\r', 1,
        '!', 84,
        '"', 7,
        '$', 25,
        '&', 8,
        '(', 82,
        ')', 76,
        '*', 97,
        '+', 96,
        ',', 75,
        '-', 86,
        '.', 26,
        '/', 98,
        ':', 80,
        '<', 91,
        '=', 45,
        '>', 94,
        '[', 16,
        ']', 46,
        '{', 77,
        '|', 24,
        '}', 78,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 35,
        '\r', 51,
        '-', 52,
        '/', 11,
        ':', 57,
        '=', 58,
        '>', 59,
        '[', 16,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(32);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '\n', 35,
        '\r', 63,
        '-', 62,
        '/', 12,
        ':', 65,
        '=', 64,
        '>', 64,
        '[', 67,
        '\t', 60,
        ' ', 60,
      );
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_node_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACKlet);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(89);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(89);
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LBRACKif);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACKelif);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACKelse);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_speaker);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '\n') ADVANCE(35);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '>') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == ':') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(55);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '>') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(53);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__bare_text);
      if (lookahead == '>') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '-' &&
          lookahead != ':' &&
          lookahead != '=' &&
          lookahead != '>') ADVANCE(53);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '\r', 63,
        '-', 62,
        '/', 12,
        ':', 65,
        '=', 64,
        '>', 64,
        '[', 67,
        '\t', 60,
        ' ', 60,
      );
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(73);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '-') ADVANCE(61);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead == '>') ADVANCE(73);
      if (lookahead == ':' ||
          lookahead == '=') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(13);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead == '>') ADVANCE(73);
      if (lookahead == '-' ||
          lookahead == ':' ||
          lookahead == '=') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '=') ADVANCE(73);
      if (lookahead == '-' ||
          lookahead == ':' ||
          lookahead == '>') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(71);
      if (lookahead == 'i') ADVANCE(69);
      if (lookahead == 'l') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'f') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'i') ADVANCE(69);
      if (lookahead == 's') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 'l') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == 't') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(37);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_attribute);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(40);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(95);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(95);
      if (lookahead == '>') ADVANCE(41);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(36);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'n') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 't') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 10:
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 4},
  [40] = {.lex_state = 4},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 33},
  [48] = {.lex_state = 33},
  [49] = {.lex_state = 32},
  [50] = {.lex_state = 32},
  [51] = {.lex_state = 32},
  [52] = {.lex_state = 32},
  [53] = {.lex_state = 32},
  [54] = {.lex_state = 32},
  [55] = {.lex_state = 32},
  [56] = {.lex_state = 32},
  [57] = {.lex_state = 32},
  [58] = {.lex_state = 32},
  [59] = {.lex_state = 32},
  [60] = {.lex_state = 32},
  [61] = {.lex_state = 32},
  [62] = {.lex_state = 32},
  [63] = {.lex_state = 32},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 3},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_LBRACKlet] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACKif] = ACTIONS(1),
    [anon_sym_LBRACKelif] = ACTIONS(1),
    [anon_sym_LBRACKelse] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_attribute] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(78),
    [sym__statement] = STATE(2),
    [sym_node_start] = STATE(2),
    [sym_jump] = STATE(2),
    [sym_choice] = STATE(2),
    [sym_command] = STATE(2),
    [sym_let_statement] = STATE(2),
    [sym_if_statement] = STATE(2),
    [sym_elif_statement] = STATE(2),
    [sym_else_statement] = STATE(2),
    [sym_say] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON_EQ] = ACTIONS(9),
    [sym_node_end] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(13),
    [anon_sym_GT_GT] = ACTIONS(15),
    [anon_sym_LBRACKlet] = ACTIONS(17),
    [anon_sym_LBRACKif] = ACTIONS(19),
    [anon_sym_LBRACKelif] = ACTIONS(21),
    [anon_sym_LBRACKelse] = ACTIONS(23),
    [sym_speaker] = ACTIONS(25),
    [sym__bare_text] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_COLON_EQ,
    ACTIONS(11), 1,
      anon_sym_EQ_GT,
    ACTIONS(13), 1,
      anon_sym_DASH_GT,
    ACTIONS(15), 1,
      anon_sym_GT_GT,
    ACTIONS(17), 1,
      anon_sym_LBRACKlet,
    ACTIONS(19), 1,
      anon_sym_LBRACKif,
    ACTIONS(21), 1,
      anon_sym_LBRACKelif,
    ACTIONS(23), 1,
      anon_sym_LBRACKelse,
    ACTIONS(25), 1,
      sym_speaker,
    ACTIONS(27), 1,
      sym__bare_text,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 2,
      sym__newline,
      sym_node_end,
    STATE(3), 11,
      sym__statement,
      sym_node_start,
      sym_jump,
      sym_choice,
      sym_command,
      sym_let_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_say,
      aux_sym_source_file_repeat1,
  [54] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      anon_sym_COLON_EQ,
    ACTIONS(41), 1,
      anon_sym_EQ_GT,
    ACTIONS(44), 1,
      anon_sym_DASH_GT,
    ACTIONS(47), 1,
      anon_sym_GT_GT,
    ACTIONS(50), 1,
      anon_sym_LBRACKlet,
    ACTIONS(53), 1,
      anon_sym_LBRACKif,
    ACTIONS(56), 1,
      anon_sym_LBRACKelif,
    ACTIONS(59), 1,
      anon_sym_LBRACKelse,
    ACTIONS(62), 1,
      sym_speaker,
    ACTIONS(65), 1,
      sym__bare_text,
    ACTIONS(35), 2,
      sym__newline,
      sym_node_end,
    STATE(3), 11,
      sym__statement,
      sym_node_start,
      sym_jump,
      sym_choice,
      sym_command,
      sym_let_statement,
      sym_if_statement,
      sym_elif_statement,
      sym_else_statement,
      sym_say,
      aux_sym_source_file_repeat1,
  [108] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(70), 1,
      anon_sym_RPAREN,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(82), 2,
      sym_number,
      sym_string,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [157] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(88), 2,
      sym_number,
      sym_string,
    STATE(38), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [206] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_attribute,
    STATE(6), 1,
      aux_sym_let_statement_repeat1,
    ACTIONS(90), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(92), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [239] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(97), 2,
      sym_number,
      sym_string,
    STATE(31), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [285] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(99), 2,
      sym_number,
      sym_string,
    STATE(46), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [331] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(101), 2,
      sym_number,
      sym_string,
    STATE(43), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [377] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 2,
      sym_number,
      sym_string,
    STATE(44), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 4,
      anon_sym_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(107), 16,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_attribute,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [451] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute,
    STATE(6), 1,
      aux_sym_let_statement_repeat1,
    ACTIONS(113), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(109), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [483] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(115), 2,
      sym_number,
      sym_string,
    STATE(37), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [529] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(117), 2,
      sym_number,
      sym_string,
    STATE(28), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [575] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(119), 2,
      sym_number,
      sym_string,
    STATE(29), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [621] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(121), 2,
      sym_number,
      sym_string,
    STATE(30), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [667] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 2,
      sym_number,
      sym_string,
    STATE(32), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [713] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(125), 2,
      sym_number,
      sym_string,
    STATE(42), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [759] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute,
    STATE(12), 1,
      aux_sym_let_statement_repeat1,
    ACTIONS(129), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(127), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [791] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(131), 2,
      sym_number,
      sym_string,
    STATE(45), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [837] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(133), 2,
      sym_number,
      sym_string,
    STATE(40), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [883] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(72), 1,
      anon_sym_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LPAREN2,
    ACTIONS(76), 1,
      anon_sym_not,
    ACTIONS(80), 1,
      sym_variable,
    STATE(19), 1,
      sym_call,
    STATE(85), 1,
      sym_function_name,
    ACTIONS(78), 2,
      anon_sym_BANG,
      anon_sym_DASH,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(135), 2,
      sym_number,
      sym_string,
    STATE(41), 7,
      sym__expression,
      sym_dict,
      sym_attribute_expression,
      sym_parenthesized_expression,
      sym_unary_expression,
      sym_binary_expression,
      sym_boolean,
  [929] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(137), 16,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_attribute,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [956] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(141), 16,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_attribute,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [983] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(145), 16,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      sym_attribute,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1010] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(127), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1039] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(151), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1065] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(155), 6,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
  [1101] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(155), 8,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
  [1135] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(155), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1167] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(155), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1193] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(171), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1219] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(175), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1245] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(179), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(183), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1297] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
    ACTIONS(187), 15,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
  [1323] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(169), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(155), 14,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
      anon_sym_and,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
  [1353] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    STATE(67), 1,
      aux_sym_call_repeat1,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1394] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      aux_sym_call_repeat1,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1435] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(199), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1471] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(201), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1507] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1542] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(205), 1,
      anon_sym_RPAREN,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1577] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(207), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1612] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1647] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_STAR,
    ACTIONS(167), 1,
      anon_sym_SLASH,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 2,
      anon_sym_DASH,
      anon_sym_PLUS,
    ACTIONS(159), 2,
      anon_sym_and,
      anon_sym_AMP_AMP,
    ACTIONS(163), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(195), 2,
      anon_sym_or,
      anon_sym_PIPE_PIPE,
    ACTIONS(161), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1682] = 4,
    ACTIONS(213), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_text,
    ACTIONS(215), 12,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
      sym__bare_text,
  [1706] = 4,
    ACTIONS(217), 1,
      sym_comment,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    ACTIONS(225), 1,
      sym_text,
    ACTIONS(223), 12,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
      sym__bare_text,
  [1730] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      sym__bare_text,
    ACTIONS(227), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1751] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym__bare_text,
    ACTIONS(137), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1772] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(233), 1,
      sym__bare_text,
    ACTIONS(231), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      sym__bare_text,
    ACTIONS(235), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1814] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      sym__bare_text,
    ACTIONS(239), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1835] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym__bare_text,
    ACTIONS(243), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1856] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym__bare_text,
    ACTIONS(247), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1877] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym__bare_text,
    ACTIONS(141), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym__bare_text,
    ACTIONS(251), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1919] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      sym__bare_text,
    ACTIONS(255), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1940] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym__bare_text,
    ACTIONS(145), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      sym__bare_text,
    ACTIONS(259), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [1982] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 1,
      sym__bare_text,
    ACTIONS(263), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [2003] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym__bare_text,
    ACTIONS(267), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [2024] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      sym__bare_text,
    ACTIONS(271), 12,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_COLON_EQ,
      sym_node_end,
      anon_sym_EQ_GT,
      anon_sym_DASH_GT,
      anon_sym_GT_GT,
      anon_sym_LBRACKlet,
      anon_sym_LBRACKif,
      anon_sym_LBRACKelif,
      anon_sym_LBRACKelse,
      sym_speaker,
  [2045] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
    STATE(73), 1,
      sym_dict_entry,
    STATE(82), 1,
      sym_dict_key,
  [2061] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      sym_identifier,
    STATE(76), 1,
      sym_dict_entry,
    STATE(82), 1,
      sym_dict_key,
  [2074] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute,
    ACTIONS(279), 1,
      anon_sym_EQ,
    STATE(70), 1,
      aux_sym_let_statement_repeat1,
  [2087] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_call_repeat1,
  [2100] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_dict_repeat1,
  [2113] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_dict_repeat1,
  [2126] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_attribute,
    ACTIONS(292), 1,
      anon_sym_EQ,
    STATE(6), 1,
      aux_sym_let_statement_repeat1,
  [2139] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_call_repeat1,
  [2152] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
    STATE(52), 1,
      sym_call,
    STATE(79), 1,
      sym_function_name,
  [2165] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RBRACE,
    STATE(68), 1,
      aux_sym_dict_repeat1,
  [2178] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(301), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_call_repeat1,
  [2191] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
    STATE(62), 1,
      sym_node_name,
  [2201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2209] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      sym_identifier,
    STATE(53), 1,
      sym_node_name,
  [2219] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      ts_builtin_sym_end,
  [2226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      anon_sym_LPAREN,
  [2233] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_variable,
  [2240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_LPAREN,
  [2247] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_COLON,
  [2254] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_RBRACK,
  [2261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      anon_sym_COLON,
  [2268] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 157,
  [SMALL_STATE(6)] = 206,
  [SMALL_STATE(7)] = 239,
  [SMALL_STATE(8)] = 285,
  [SMALL_STATE(9)] = 331,
  [SMALL_STATE(10)] = 377,
  [SMALL_STATE(11)] = 423,
  [SMALL_STATE(12)] = 451,
  [SMALL_STATE(13)] = 483,
  [SMALL_STATE(14)] = 529,
  [SMALL_STATE(15)] = 575,
  [SMALL_STATE(16)] = 621,
  [SMALL_STATE(17)] = 667,
  [SMALL_STATE(18)] = 713,
  [SMALL_STATE(19)] = 759,
  [SMALL_STATE(20)] = 791,
  [SMALL_STATE(21)] = 837,
  [SMALL_STATE(22)] = 883,
  [SMALL_STATE(23)] = 929,
  [SMALL_STATE(24)] = 956,
  [SMALL_STATE(25)] = 983,
  [SMALL_STATE(26)] = 1010,
  [SMALL_STATE(27)] = 1039,
  [SMALL_STATE(28)] = 1065,
  [SMALL_STATE(29)] = 1101,
  [SMALL_STATE(30)] = 1135,
  [SMALL_STATE(31)] = 1167,
  [SMALL_STATE(32)] = 1193,
  [SMALL_STATE(33)] = 1219,
  [SMALL_STATE(34)] = 1245,
  [SMALL_STATE(35)] = 1271,
  [SMALL_STATE(36)] = 1297,
  [SMALL_STATE(37)] = 1323,
  [SMALL_STATE(38)] = 1353,
  [SMALL_STATE(39)] = 1394,
  [SMALL_STATE(40)] = 1435,
  [SMALL_STATE(41)] = 1471,
  [SMALL_STATE(42)] = 1507,
  [SMALL_STATE(43)] = 1542,
  [SMALL_STATE(44)] = 1577,
  [SMALL_STATE(45)] = 1612,
  [SMALL_STATE(46)] = 1647,
  [SMALL_STATE(47)] = 1682,
  [SMALL_STATE(48)] = 1706,
  [SMALL_STATE(49)] = 1730,
  [SMALL_STATE(50)] = 1751,
  [SMALL_STATE(51)] = 1772,
  [SMALL_STATE(52)] = 1793,
  [SMALL_STATE(53)] = 1814,
  [SMALL_STATE(54)] = 1835,
  [SMALL_STATE(55)] = 1856,
  [SMALL_STATE(56)] = 1877,
  [SMALL_STATE(57)] = 1898,
  [SMALL_STATE(58)] = 1919,
  [SMALL_STATE(59)] = 1940,
  [SMALL_STATE(60)] = 1961,
  [SMALL_STATE(61)] = 1982,
  [SMALL_STATE(62)] = 2003,
  [SMALL_STATE(63)] = 2024,
  [SMALL_STATE(64)] = 2045,
  [SMALL_STATE(65)] = 2061,
  [SMALL_STATE(66)] = 2074,
  [SMALL_STATE(67)] = 2087,
  [SMALL_STATE(68)] = 2100,
  [SMALL_STATE(69)] = 2113,
  [SMALL_STATE(70)] = 2126,
  [SMALL_STATE(71)] = 2139,
  [SMALL_STATE(72)] = 2152,
  [SMALL_STATE(73)] = 2165,
  [SMALL_STATE(74)] = 2178,
  [SMALL_STATE(75)] = 2191,
  [SMALL_STATE(76)] = 2201,
  [SMALL_STATE(77)] = 2209,
  [SMALL_STATE(78)] = 2219,
  [SMALL_STATE(79)] = 2226,
  [SMALL_STATE(80)] = 2233,
  [SMALL_STATE(81)] = 2240,
  [SMALL_STATE(82)] = 2247,
  [SMALL_STATE(83)] = 2254,
  [SMALL_STATE(84)] = 2261,
  [SMALL_STATE(85)] = 2268,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(72),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_let_statement_repeat1, 2, 0, 13),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_statement_repeat1, 2, 0, 13),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_let_statement_repeat1, 2, 0, 13), SHIFT_REPEAT(11),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_let_statement_repeat1, 1, 0, 8),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_let_statement_repeat1, 1, 0, 8),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_expression, 2, 0, 10),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_expression, 2, 0, 10),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 3, 0, 12),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 3, 0, 12),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 4, 0, 12),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 4, 0, 12),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 5, 0, 12),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 5, 0, 12),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 14),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 14),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 9),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 9),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 4, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict, 2, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dict, 2, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict_entry, 3, 0, 16),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 1, 0, 1),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 1, 0, 1),
  [217] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_choice, 2, 0, 5),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_choice, 2, 0, 5),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 6),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 6),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump, 2, 0, 4),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump, 2, 0, 4),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 2, 0, 7),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 2, 0, 7),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 11),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 11),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 15),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 5, 0, 15),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_name, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_name, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 6, 0, 17),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 6, 0, 17),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elif_statement, 3, 0, 11),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elif_statement, 3, 0, 11),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node_start, 2, 0, 3),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node_start, 2, 0, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_say, 1, 0, 2),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_say, 1, 0, 2),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [287] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dict_repeat1, 2, 0, 0),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [305] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dict_key, 1, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_replique(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "replique",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
